name: base
channels:
  - defaults
dependencies:
  - anaconda-anon-usage=0.7.4
  - anaconda-auth=0.10.0
  - anaconda-cli-base=0.6.0
  - anaconda_powershell_prompt=1.1.0
  - anaconda_prompt=1.1.0
  - annotated-types=0.6.0
  - archspec=0.2.5
  - boltons=25.0.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.1.8
  - colorama=0.4.6
  - conda=25.9.1
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.4.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - cpp-expected=1.1.0
  - cryptography=46.0.3
  - distro=1.9.0
  - expat=2.7.3
  - fmt=11.2.0
  - frozendict=2.4.6
  - idna=3.11
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - keyring=25.6.0
  - libarchive=3.8.2
  - libcurl=8.16.0
  - libffi=3.4.4
  - libiconv=1.16
  - libmamba=2.3.2
  - libmambapy=2.3.2
  - libmpdec=4.0.0
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - mdurl=0.1.2
  - menuinst=2.4.1
  - more-itertools=10.8.0
  - nlohmann_json=3.11.2
  - openssl=3.0.18
  - packaging=25.0
  - pcre2=10.46
  - pip=25.2
  - pkce=1.0.3
  - platformdirs=4.5.0
  - pluggy=1.5.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.23
  - pydantic=2.12.3
  - pydantic-core=2.41.4
  - pydantic-settings=2.10.1
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pysocks=1.7.1
  - python=3.13.9
  - python-dotenv=1.1.0
  - python_abi=3.13
  - pywin32-ctypes=0.2.2
  - readchar=4.2.1
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.5
  - rich=14.2.0
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - semver=3.0.4
  - setuptools=80.9.0
  - shellingham=1.5.4
  - simdjson=3.10.1
  - sqlite=3.51.0
  - tk=8.6.15
  - tomli=2.2.1
  - tqdm=4.67.1
  - truststore=0.10.1
  - typer=0.17.4
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zlib=1.3.1
  - zstandard=0.24.0
  - zstd=1.5.7
  - pip:
      - anyio==4.11.0
      - filelock==3.20.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.5
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.5
      - pillow==12.0.0
      - pyyaml==6.0.3
      - safetensors==0.7.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - timm==1.0.22
      - torchvision==0.24.1
      - typer-slim==0.20.0
