name: cv-amm-hw
channels:
  - defaults
dependencies:
  - numpy=2.2.5
  - sip=6.12.0
  - numpy-base=2.2.5
  - pcre2=10.46
  - tqdm=4.67.1
  - executing=2.2.1
  - mkl-service=2.5.2
  - platformdirs=4.5.0
  - comm=0.2.3
  - jupyter_client=8.6.3
  - nest-asyncio=1.6.0
  - wcwidth=0.2.13
  - fontconfig=2.15.0
  - pillow=12.0.0
  - graphite2=1.3.14
  - libkrb5=1.21.3
  - tomli=2.2.1
  - pixman=0.46.4
  - aom=3.12.1
  - qtsvg=6.9.2
  - libzlib=1.3.1
  - libffi=3.4.4
  - freeglut=3.4.0
  - libpng=1.6.50
  - matplotlib-base=3.10.6
  - mkl_fft=2.1.1
  - tk=8.6.15
  - zeromq=4.3.5
  - vc=14.3
  - wheel=0.45.1
  - parso=0.8.5
  - libxml2=2.13.9
  - pytz=2025.2
  - libdeflate=1.22
  - contourpy=1.3.1
  - asttokens=3.0.0
  - ucrt=10.0.22621.0
  - psutil=7.0.0
  - bzip2=1.0.8
  - harfbuzz=10.2.0
  - mysql-common=9.3.0
  - fribidi=1.0.10
  - tornado=6.5.1
  - pywin32=311
  - intel-openmp=2025.0.0
  - mysql-libs=9.3.0
  - python-dateutil=2.9.0post0
  - pure_eval=0.2.3
  - pyparsing=3.2.0
  - python=3.10.19
  - libwebp-base=1.3.2
  - sqlite=3.51.0
  - bottleneck=1.4.2
  - cairo=1.18.4
  - libpq=17.6
  - mkl_random=1.3.0
  - pandas=2.3.3
  - qtwebchannel=6.9.2
  - tzdata=2025b
  - setuptools=80.9.0
  - numexpr=2.14.1
  - debugpy=1.8.16
  - colorama=0.4.6
  - libavif=1.1.1
  - python_abi=3.10
  - pyqt=6.9.1
  - vs2015_runtime=14.44.35208
  - icu=73.1
  - libsodium=1.0.20
  - zstd=1.5.7
  - stack_data=0.6.3
  - pip=25.3
  - xz=5.6.4
  - lz4-c=1.9.4
  - kiwisolver=1.4.8
  - ca-certificates=2025.11.4
  - pyqt6-sip=13.10.2
  - blas=1.0
  - qttools=6.9.2
  - lcms2=2.16
  - matplotlib-inline=0.2.1
  - ipykernel=6.31.0
  - qtwebsockets=6.9.2
  - exceptiongroup=1.3.0
  - zlib=1.3.1
  - matplotlib=3.10.6
  - pygments=2.19.2
  - cycler=0.11.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - jpeg=9f
  - vc14_runtime=14.44.35208
  - expat=2.7.3
  - prompt-toolkit=3.0.52
  - jedi=0.19.2
  - qtbase=6.9.2
  - libiconv=1.16
  - ipython=8.30.0
  - tbb=2022.0.0
  - openssl=3.0.18
  - prompt_toolkit=3.0.52
  - six=1.17.0
  - traitlets=5.14.3
  - libglib=2.84.4
  - libtiff=4.7.0
  - typing-extensions=4.15.0
  - packaging=25.0
  - dav1d=1.2.1
  - decorator=5.2.1
  - libopenjpeg=2.5.4
  - jupyter_core=5.8.1
  - qtdeclarative=6.9.2
  - tbb-devel=2022.0.0
  - lerc=4.0.0
  - pyzmq=27.1.0
  - python-tzdata=2025.2
  - mkl=2025.0.0
  - typing_extensions=4.15.0
prefix: C:\Users\marci\miniconda3\envs\cv-amm-hw
